### ISSUE TITLE
MySQL?

### ISSUE THREAD

**Issue by m1guelpf** [shargon/PhpRequestLog#2]
Hi!
I tried to make a tool like this a few weeks ago (https://github.com/m1guelpf/MPCms) but the admin page load takes ages, so I decided to stop working on this.
Today, I've seen your projects and I am wondering what should I modify to use a MySQL database instead of a txt file. (You can see how my mysql system worked at the index, config and functions.php in the m1guelpf/MPCms or in my new project at https://github.com/m1guelpf/Activity).

**Comment by shargon** [comment]
Tomorrow. I upload new version with mysql store method ;)

**Comment by m1guelpf** [comment]
Thank you!
Could you please ping me when done?

**Comment by shargon** [comment]
Done :)
uncomment the file or mysql version

**Comment by m1guelpf** [comment]
Can you provide a db dump?
Thank you
